//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public int GROUP_ID { get; set; }
        public string GROUP1 { get; set; }
        public Nullable<int> FK_COURSE_ID { get; set; }
        public Nullable<int> FK_SPECIALITY_ID { get; set; }
        public Nullable<int> FK_FACULTY_ID { get; set; }
        public Nullable<int> FK_TEACHER_ID { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual FACULTY FACULTY { get; set; }
        public virtual SPECIALITY SPECIALITY { get; set; }
        public virtual USER USER { get; set; }
    }
}
