//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK
    {
        public int MARK_ID { get; set; }
        public string MARK1 { get; set; }
        public Nullable<int> FK_SUBJECT_ID { get; set; }
        public Nullable<int> FK_STUDENT_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual SUBJECT SUBJECT { get; set; }
        public virtual USER USER { get; set; }
    }
}
