//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gr691_mnmEntities : DbContext
    {
        public gr691_mnmEntities()
            : base("name=gr691_mnmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COURSE> COURSE { get; set; }
        public virtual DbSet<FACULTY> FACULTY { get; set; }
        public virtual DbSet<GROUP> GROUP { get; set; }
        public virtual DbSet<MARK> MARK { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<SPECIALITY> SPECIALITY { get; set; }
        public virtual DbSet<SUBJECT> SUBJECT { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<SUBJECT_GROUP> SUBJECT_GROUP { get; set; }
    }
}
